### ISSUE TITLE
SPIKE: SICK units sometimes need re-plugged in

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-rust-terminal#36]

**Comment by SebastianNeiswanger** [comment]
Doing some testing I found that even if a computer has no internet the heartbeat will "connect." This means that it will send the messages and wait. It won't remove the local check-ins since it never gets a response, but we also aren't retrying to connect. We might want to try [zmq-socket-monitor](http://api.zeromq.org/4-1:zmq-socket-monitor) to determine whether the connection is actually good.
